apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: nginx